### ISSUE TITLE
from old URL to New URL

### ISSUE THREAD

**Issue by Inkimar** [Naturhistoriska/swedishbirdrecoveries#1]
1. The old URL -> birdringing.bioatlas.se/ 
2. should go to -> https://birdrecoveries.nrm.se/

**Comment by Inkimar** [comment]
The rerouting has been done by @shahmanash

**Comment by thomwenn** [comment]
Sorry, the move didn´t work completely. It seems that the application only uses the original data set from 2017. 

Update is produced every night to make the content up-to-date. 
The chain is: 
SQL-server NRMMSSQL01: 
database "Ring", stored procedure "dbo.Fyll_Webbdata" into table "dbo.Webbdata"
Then by unknown procedure transfered into file 
"193.10.57.61\home\thomas\fagel\aterfynd\SQLDataExport.csv"
wherefrom the data is transferred to the application. (With 24 hours unnecessary delay.)

**Comment by shahmanash** [comment]
The update of the data is not related to moving of the url.

**Comment by thomwenn** [comment]
Something must have been affected by the actions taken last week. Before this all worked well and displayed the most recent data. Now there is no data at all from the last two years. I haven´t changed anything and I can see that the file SQLDataExport.csv is new.

I´m sorry, but I don´t know anything about the code in this project, so I cannot find where to correct. And because of this I certainly have not made any alterations to it.

**Comment by Inkimar** [comment]
Looking closer into the nrmbirdringing.nrm.se machine, can it reach the  following machine 'http://fagel3.nrm.se/fagel/aterfynd/SQLDataExport.csv'

-> here is the code with the URL to the  'SQLDataExport.csv'
https://github.com/mskyttner/swedishbirdrecoveries/blob/master/R/update.R

**Comment by Inkimar** [comment]
could it be that MS goes to the sqlite-database if he cannot reach the URL ?
See code https://github.com/mskyttner/swedishbirdrecoveries/blob/master/R/update.R#L93-L101

**Comment by Inkimar** [comment]
Fixed.
missing file -> refresh-swedishbirdrecoveries.sh , should be run daily by cron
